---
title: "p8105_hw4_bl2689"
author: "Boxuan Li"
date: "10/23/2017"
output: html_document
---
# Load packages and set the tibble display length.
```{r, message=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(haven)
library(readxl)
library(janitor)
library(ggridges)
library(rnoaa)

options(tibble.print_min = 10)
```

# Read the dataset "FAS_Puls" and basically tidy it.
```{r, message=FALSE}
Puls.raw <- read_csv("./data/FAS_pups.csv") %>%
  clean_names() %>%
  separate(., litter_number, into = c("del", "litter_number"), sep = 1) %>%
  select(., everything(), -del) %>%
  gather(., key = "pd_outcome", value = "postnatal_days", pd_ears:pd_walk, na.rm = T) %>%
  arrange(., litter_number)
```
# Plot of distribution of post-natal days for each developmental landmark
```{r}
Puls.raw %>% 
  group_by(pd_outcome) %>% 
  ggplot(aes(x = postnatal_days, y = pd_outcome, fill = pd_outcome)) +
  geom_density_ridges(alpha = 0.5) +
  theme(legend.position = "bottom") +
  labs(
    title = "Distribution of post-natal days for each developmental landmark",
    x = "postnatal days",
    y = "pd names"
  )
```